#Copyright IBM Corp. All Rights Reserved.
#SPDX-License-Identifier: Apache-2.0

[[constraint]]
  version = "0.18.0"
  name = "github.com/hyperledger/burrow"

[[constraint]]
  branch = "master"
  name = "github.com/hyperledger/fabric"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[constraint]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[constraint]]
  version = "1.0.0-alpha3"
  name = "github.com/hyperledger/fabric-sdk-go"

[[override]]
  version = "~0.6.0"
  name = "github.com/tendermint/tmlibs"

#From Fabric
[[override]]
  revision = "57142e89befe90977da6dce7762f9fcc70f28da1"
  name = "github.com/docker/docker"

#From Fabric?
[[override]]
  version = "0.8.0"
  name = "github.com/pkg/errors"

#From fabric-sdk-go
[[override]]
  revision = "aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5"
  name = "github.com/spf13/viper"

#From Fabric
[[override]]
  name = "github.com/golang/protobuf"
  revision = "fec3b39b059c0f88fa6b20f5ed012b1aa203a8b4"

[prune]
  go-tests = true
  unused-packages = true
